spring:
  redis:
    host: 114.67.102.1
    port: 6379
    jedis:
      pool:
        max-active: 18
        max-idle: 8
        time-between-eviction-runs: 5000
    timeout: 2000
  application:
    name: redis-service
server:
  port: 8001
